{application,base64url,
             [{description,"URL safe base64-compatible codec"},
              {vsn,"1.0.1"},
              {id, "v3.10.6-41-g04ce6e5"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {licenses,["MIT"]},
              {links,[{"Github","https://github.com/dvv/base64url"}]},
              {modules, ['base64url']}]}.
