{application,seshat,
             [{description,"Counters registry"},
              {vsn,"0.3.2"},
              {licenses,["Apache","MPL"]},
              {links,[{"github","https://github.com/rabbitmq/seshat"}]},
              {modules, ['seshat','seshat_app','seshat_counters_server','seshat_sup']},
              {registered,[seshat_sup]},
              {applications,[kernel,stdlib,sasl,crypto]},
              {mod,{seshat_app,[]}},
              {env,[]}]}.
